### ISSUE TITLE
Blog index previews are auto-escaping some characters

### ISSUE THREAD

**Issue by craigcook** [mozmeao/birdbox#134] opened 2023-10-09 16:49 UTC
Characters such as curly quotes and apostrophes are sometimes being rendered as unescaped entities in the post preview card:

![image](https://github.com/mozmeao/birdbox/assets/205591/49850ce3-b31b-4bf8-aa75-c7d8436734c4)

**Comment by craigcook** [comment] 2023-10-09 17:21
Right now this is appearing on prod, where the blog index and the one post are both still saved as drafts. I tried to fix that apostrophe in the post draft but the change isn't appearing on the index, perhaps _because_ it's a draft and that would be fixed upon publication. Or else previews don't update when posts update, regardless of published status, which is also a problem. When post content changes the preview should change as well.

So this may not be an encoding/escaping problem after all and might have just been a content error that in turn exposed a different problem with the way post blurbs are generated.

**Comment by stevejalim** [comment] 2023-10-09 19:53
I've re-published the post that had the wonky preview and the encoding issue has gone away. Let's close this for now as can't reproduce - [re]publishing certainly fixed it

**Closed by stevejalim** 2023-10-09 19:53 UTC

**Comment by stevejalim** [comment] 2023-10-10 08:16
Thinking about this a bit more, we _could_ do some (post-MVP) work that detects whether the user is viewing a preview of the blog index page or not, and then gets draft posts, not published ones, accordingly.

**Comment by stevejalim** [comment] 2023-10-10 11:04
OK I went ahead and did it now, because I spotted a bug where a draft post would leak into a published live index page -  https://github.com/mozmeao/birdbox/pull/136
